/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface OrganizationGetProjectWorkloadsRequest {
    /**
     * Project IDs
     */
    projects: Array<string>;
    /**
     * Starting time (in seconds from epoch) for collecting statistics
     */
    from_date: string;
    /**
     * Ending time (in seconds from epoch) for collecting statistics. Pass null for   now
     */
    to_date: string;
    /**
     * If set to \'true\' then development tasks are also returned
     */
    include_development?: boolean;
    breakdown_keys?: Array<OrganizationGetProjectWorkloadsRequest.BreakdownKeysEnum>;
    usage_fields?: Array<OrganizationGetProjectWorkloadsRequest.UsageFieldsEnum>;
}
export namespace OrganizationGetProjectWorkloadsRequest {
    export type BreakdownKeysEnum = 'project' | 'user' | 'queue';
    export const BreakdownKeysEnum = {
        Project: 'project' as BreakdownKeysEnum,
        User: 'user' as BreakdownKeysEnum,
        Queue: 'queue' as BreakdownKeysEnum
    }
    export type UsageFieldsEnum = 'duration' | 'cpu_usage' | 'gpu_usage';
    export const UsageFieldsEnum = {
        Duration: 'duration' as UsageFieldsEnum,
        CpuUsage: 'cpu_usage' as UsageFieldsEnum,
        GpuUsage: 'gpu_usage' as UsageFieldsEnum
    }
}
