/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface WorkloadsSeries {
    name?: string;
    id?: string;
    /**
     * Date timestamp in seconds
     */
    dates?: Array<number>;
    /**
     * Tasks running time in seconds
     */
    duration?: Array<number>;
    /**
     * Tasks running task multiplied by cpu resource
     */
    cpu_usage?: Array<number>;
    /**
     * Tasks running task multiplied by gpu resource
     */
    gpu_usage?: Array<number>;
    /**
     * Indicate whether artificial cpu resource weights were used
     */
    cpu_usage_artifical_weights?: boolean;
    /**
     * Indicate whether artificial gpu resource weights were used
     */
    gpu_usage_artifical_weights?: boolean;
}
