/**
 * queues
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MetadataItem } from '././metadataItem';


export interface QueuesAddOrUpdateMetadataRequest {
    /**
     * ID of the queue
     */
    queue: string;
    /**
     * Metadata items to add or update
     */
    metadata: Array<MetadataItem>;
    /**
     * If set then the all the metadata items will be replaced with the provided ones.   Otherwise only the provided metadata items will be updated or added
     */
    replace_metadata?: boolean;
}
