/**
 * queues
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Queue } from '././queue';


export interface QueuesGetAllResponse {
    /**
     * Queues list
     */
    queues?: Array<Queue>;
    /**
     * Scroll ID that can be used with the next calls to get_all to retrieve more data
     */
    scroll_id?: string;
}
