/**
 * queues
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { QueuesGetAllExRequestAll } from '././queuesGetAllExRequestAll';
import { QueuesGetAllExRequestAny } from '././queuesGetAllExRequestAny';


/**
 * Filter on a field that includes combination of \'any\' or \'all\' included and excluded terms
 */
export interface QueuesGetAllExRequestFilters {
    any?: QueuesGetAllExRequestAny;
    all?: QueuesGetAllExRequestAll;
    /**
     * The operation between \'any\' and \'all\' parts of the filter if both are provided
     */
    op?: QueuesGetAllExRequestFilters.OpEnum;
}
export namespace QueuesGetAllExRequestFilters {
    export type OpEnum = 'and' | 'or';
    export const OpEnum = {
        And: 'and' as OpEnum,
        Or: 'or' as OpEnum
    }
}
