/**
 * queues
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * Profile connection for policy queues
 */
export interface QueueProfileConnection {
    /**
     * Profile ID
     */
    profile?: string;
    /**
     * Policy ID
     */
    policy?: string;
    /**
     * Policy Name. Returned only for admins or members of the corresponding policy group
     */
    policy_name?: string;
    /**
     * Policy group
     */
    user_group?: string;
}
