/**
 * queues
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * Info about the returned task. Returned only if get_task_info is set to True
 */
export interface QueuesGetNextTaskResponseTaskInfo {
    /**
     * Task company ID
     */
    company?: string;
    /**
     * ID of the user who created the task
     */
    user?: string;
}
