/**
 * queues
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface QueuesAddTaskRequest {
    /**
     * Queue id
     */
    queue: string;
    /**
     * Task id
     */
    task: string;
    /**
     * If set to Falsethen the task \'execution.queue\' is not updated
     */
    update_execution_queue?: boolean;
}
