/**
 * queues
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Entry } from '././entry';
import { MetadataItem } from '././metadataItem';


export interface Queue {
    /**
     * Queue id
     */
    id?: string;
    /**
     * Queue name
     */
    name?: string;
    /**
     * Display name
     */
    display_name?: string;
    /**
     * Associated user id
     */
    user?: string;
    /**
     * Company id
     */
    company?: string;
    /**
     * Queue creation time
     */
    created?: string;
    /**
     * User-defined tags
     */
    tags?: string[];
    /**
     * System tags. This field is reserved for system use, please don\'t use it.
     */
    system_tags?: string[];
    /**
     * List of ordered queue entries
     */
    entries?: Entry[];
    /**
     * Queue metadata
     */
    metadata?: Record<string, MetadataItem>;
    /**
     * Queue last update
     */
    last_update?: string;
    workers?: Worker[];
    // profile_connection?: QueueProfileConnection;
    /**
    * Number of entries in the queue
    */
    entries_count?: number;
}
