/**
 * pipelines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface PipelinesCheckNewRunRequest {
    /**
     * ID of the existing controller task
     */
    task: string;
    /**
     * The name of the target project
     */
    new_project_name: string;
    /**
     * The name of the pipeline. If not passed then the controller task name is used
     */
    new_pipeline_name?: string;
}
