/**
 * pipelines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * In case the project_name was specified returns the target project details
 */
export interface PipelinesStartPipelineResponseNewProject {
    /**
     * The ID of the target project
     */
    id?: string;
    /**
     * The name of the target project
     */
    name?: string;
}
