/**
 * pipelines
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PipelinesStartPipelineRequestArgs } from '././pipelinesStartPipelineRequestArgs';


export interface PipelinesStartPipelineRequest {
    /**
     * ID of the task on which the pipeline will be based
     */
    task: string;
    /**
     * Queue ID in which the created pipeline task will be enqueued
     */
    queue?: string;
    /**
     * Task arguments, name/value to be placed in the hyperparameters Args section
     */
    args?: Array<PipelinesStartPipelineRequestArgs>;
    /**
    * If passed then check wheter there are any workers watiching the queue
    */
    verify_watched_queue?: boolean;
    /**
     * Existing project name to start a pipeline in. If not provider then run in the   current project
     */
    new_project_name?: string;
    /**
     * New pipeline name to start a pipeline in. Used only if new project name is   passed. If not passed then task name is used
     */
    new_pipeline_name?: string;
    /**
     * The run number to start with
     */
    new_pipeline_run?: number;
}
